#!/bin/bash
#
# Script name: bootstrap
# Description: Install dependencies necessary to build and install suckless dwm.
# Dependencies:
# GitHub: https://github.com/ifcodesdotnet/.dotfiles-dwm
# Contributors: Ismael Fernandez

source $HOME/.dotfiles-dwm/scripts/bootstrap/bootstrap-variables/apt-packages

sudo echo > /dev/null 2>&1

update_apt(){
  echo updating apt cache.

  sudo apt update
  if [ $? -ne 0 ];
  then
      clear
      echo failure updating apt cache.
      exit
  fi

  echo completed updating apt cache
}

upgrade_apt(){
  echo upgrading apt packages.

  sudo apt upgrade -y
  if [ $? -ne 0 ];
  then
      clear
      echo failure upgrading apt packages.
      exit
  fi

  echo completed upgrading apt packages.
}

install_apt_packages(){
  echo installing apt packages.

  for package in "${!apt_packages[@]}";
  do
    echo installing ${apt_packages[$package]} and dependencies.
    echo
    sleep 1

    sudo apt install -y ${apt_packages[$package]}
    if [ $? -ne 0 ];
    then
        clear
        echo failure installing ${apt_packages[$package]}.
        exit
    fi
  done

  echo completed installing apt packages.
}

clone_suckless_forks(){
  mkdir ~/Source
  git -C ~/Source git clone https://www.github.com/ifcodesdotnet/dwm
  git -C ~/Source git clone https://www.github.com/ifcodesdotnet/st
  #git -C ~/Source git clone https://www.github.com/ifcodesdotnet/dmenu
}

add_suckless_upstream_remotes(){
  git -C ~/Source/dwm remote add upstream https://git.suckless.org/dwm
  git -C ~/Source/st remote add upstream https://git.suckless.org/st
  #git -C ~/Source/dmenu remote add upstream https://git.suckless.org/dmenu
}

update_apt
upgrade_apt
install_apt_packages
clone_suckless_forks
add_suckless_upstream_remotes




#Cloning my forks of apps
#git clone https://www.github.com/ifcodesdotnet/dwm
#git clone https://www.github.com/ifcodesdotnet/st
#git clone https://www.github.com/ifcodesdotnet/dmenu

#Adding upstream remotes
#git remote add suckless https://git.suckless.org/dwm
#git remote add suckless https://git.suckless.org/st
#git remote add suckless https://git.suckless.org/dmenu