#!/bin/bash
#
# Script name: bootstrap
# Description: Install dependencies necessary to build and install suckless dwm.
# Dependencies:
# GitHub: https://github.com/ifcodesdotnet/.dotfiles-dwm
# Contributors: Ismael Fernandez

source $HOME/.dotfiles-dwm/scripts/bootstrap/bootstrap-variables/apt-packages
source $HOME/.dotfiles-dwm/scripts/bootstrap/bootstrap-variables/suckless-software

sudo echo > /dev/null 2>&1

update_apt_cache(){
  echo updating apt cache.

  sudo apt update -y
  if [ $? -ne 0 ];
  then
      clear
      echo failure updating apt cache.
      exit
  fi
}

upgrade_apt_packages(){
  echo upgrading apt packages.

  sudo apt upgrade -y
  if [ $? -ne 0 ];
  then
      clear
      echo failure upgrading apt packages.
      exit
  fi
}

install_apt_packages(){
  for package in "${!apt_packages[@]}";
  do

    sudo apt install -y ${apt_packages[$package]}
    if [ $? -ne 0 ];
    then
        clear
        echo failure installing ${apt_packages[$package]}.
        exit
    fi
  done
}

clone_suckless_forks(){
  if [ ! -d "$HOME/Source" ]
  then
      mkdir ~/Source
  fi

  for application in "${!suckless_software[@]}";
  do
    if [ ! -d "$HOME/Source/"${suckless_software[$application]} ]
    then
       git -C ~/Source clone https://www.github.com/ifcodesdotnet/${suckless_software[$application]}
    fi
  done
}

add_suckless_upstream_remotes(){
  for application in "${suckless_software[@]}";
  do
    if [ -d "$HOME/Source/"${suckless_software[$application]} ]
    then
       git -C ~/Source/${suckless_software[$application]} remote add upstream https://git.suckless.org/${suckless_software[$application]}
    fi
  done
}

apply_stow_configs(){
  stow -v -d $HOME/.dotfiles-dwm/configs -t $HOME/ x11
  stow -v -d $HOME/.dotfiles-dwm/configs -t $HOME/ vim
  sudo stow -v -d $HOME/.dotfiles-dwm/configs -t /etc etc
}


#not working correctly
build_programs(){
  for application in "${suckless_software[@]}";
  do
    if [ -d "$HOME/Source/"${suckless_software[$application]} ]
    then
       sudo make -C ~/Source/${suckless_software[$application]} clean install
    fi
  done
}

#not working correctly
enable_services(){
  sudo systemctl enable lock.service
}

update_apt_cache
upgrade_apt_packages
install_apt_packages
clone_suckless_forks
add_suckless_upstream_remotes
apply_stow_configs
build_programs
enable_services